---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 48522.
--- DateTime: 2026/3/24 10:16
---
local key = KEYS[1]
local limit = tonumber(ARGV[1])
local start = tonumber(ARGV[2])
local now = tonumber(ARGV[3])
local uuid = ARGV[4]
local request = tonumber(redis.call("zcount",key,start,now))
if request + 1 > limit then
    return false
else
    redis.call("zadd",key,now,uuid)
    redis.call("zremrangebyscore",key,0,start)
    return true
end

